apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fagprove-backend
  namespace: fint-core
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fagprove-backend:latest
  kafka:
    enabled: true
    acls:
      - topic: '*.fint-core.event.*'
        permission: admin
  observability:
    metrics:
      enabled: true
      port: "8080"
      path: /actuator/prometheus
  database:
    database: fint-core
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx525M'
  resources:
    limits:
      memory: "1Gi"
      cpu: "500m"
    requests:
      memory: "500Mi"
      cpu: "100m"