fint:
  kafka:
    default-replicas: 1
    application-id: fagprove-backend

spring:
  kafka:
    consumer:
      group-id: fagprove-backend

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/fagprove-test
    password: postgres


management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"